### ISSUE TITLE
Create API Routes

### ISSUE THREAD

**Issue by reenphygeorge** [reenphygeorge/lab-management#7]
### API ROUTES

- [x]  /user

        Method: GET
        Payload: authID
        Response:  **All Data**

- [x]  /user

        Method: PATCH
        Payload: 
        {
                authID
                collegeID,
                name,
                department,
                email,
                phone,
        }

- [x]  /department

        Method: GET
        Payload: N/A
        Response: **All Data**

**Comment by benjaminj26** [comment]
Implemented these routes
